#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
  ------ Train SAE and DAE ------
  Created by Xiaolin Wan, 5.10.2016

  Draft* Do NOT cite.
"""

import os
import sys
import time

from text_autoencoder import SAE, DAE

trainig_parameters = {
    # Parameters for SAE and DAE
    'vocab_size',
    'word_emb_dim',
    'sentence_emb_dim',
    'dec_nsteps',
    'use_dropout'

    # Parameters for training
    'optimizer',
    'patience',
    'max_epochs',
    'lrate',
    'decay',
    'moment'
    'valid_freq',
    'batch_size',
    'valid_batch_size'

    # Extra option
    'disp_freq',
    'save_freq',
    'loadfrom'
    'saveto',
}
